import type { Language } from './i18n';

// Source copy stays beside its English translation; identifiers and user content are never translated.
const english: Record<string, string> = {
  "Nile 시연": "Nile demo",
  "USDT 예상 개요": "USDT estimates",
  "USDT 요구 분석": "USDT needs analysis",
  "USDT 가정 계산": "USDT scenario calculation",
  "Mainnet 시장 데이터": "Mainnet market data",
  "목표 감시·기록 검토": "Goal monitoring and records",
  "연결 상태": "Connection status",
  "연결은 주소 조회입니다. Nile 시험 거래는 별도 미리보기와 확인 후에만 서명합니다.": "Connecting only reads your address. Nile test transactions require a separate preview and confirmation before signing.",
  "현재 변경 내용을 브라우저에 저장하지 못했습니다. 아래에서 JSON을 내보내 보관해 주세요.": "Your changes could not be saved in this browser. Export the JSON below to keep a backup.",
  "원본 백업 또는 새 세션 저장에 실패했습니다. 먼저 원본 JSON을 내려받고 브라우저 저장 공간을 확인해 주세요.": "The original backup or new session could not be saved. Download the original JSON first and check browser storage.",
  "복구 파일이 현재 세션 형식에 맞지 않거나 저장에 실패했습니다. 원본 세션은 유지했습니다.": "The recovery file is incompatible or could not be saved. Your original session has been preserved.",
  "시장 조회에 실패했습니다.": "Market lookup failed.",
  "Nile RPC 연결 실패": "Nile RPC connection failed",
  "주소 연결을 확인했습니다. Nile 거래는 별도 미리보기와 사용자님 확인이 필요합니다.": "Address connection verified. Nile transactions require a separate preview and your confirmation.",
  "지갑 연결이 취소되었습니다.": "Wallet connection was cancelled.",
  "입력값을 확인해 주세요.": "Please check your inputs.",
  "지출·여유 확보": "Expenses and reserve",
  "지출 확보": "Protected expenses",
  "운용 기간 이후의 지출도 지금부터 확보해 둡니다.": "Expenses after the investment period are also set aside now.",
  "예정 지출과 추가 여유액을 합친 금액입니다.": "Scheduled expenses plus your additional reserve.",
  "예정 지출을 위해 확보한 금액입니다.": "Funds set aside for scheduled expenses.",
  "Nile 기술 시연": "Nile technical demo",
  "Nile 테스트넷": "Nile testnet",
  "시장 조회": "Market lookup",
  "Mainnet 시장": "Mainnet markets",
  "연결 확인": "Connection check",
  "지갑·Nile 상태": "Wallet / Nile status",
  "기록 검토": "Records",
  "체인별 근거": "Evidence by chain",
  "요구 분석": "Needs analysis",
  "체인별 입력": "Inputs by chain",
  "가정 시연": "Scenario demo",
  "USDT 예상": "USDT estimates",
  "저장된 세션을 복구한 뒤 Nile 거래를 진행해 주세요.": "Restore the saved session before making a Nile transaction.",
  "예치 전 같은 포지션의 실관측이 아닙니다.": "This is not a live observation of the same position before deposit.",
  "확정된 원 환매 거래와 TRX 실수령 근거가 일치하지 않습니다.": "The confirmed original redemption does not match the evidence of TRX received.",
  "TROMM 홈": "TROMM home",
  "주요 메뉴": "Main navigation",
  "USDT 계산": "USDT calculator",
  "시장 데이터": "Market data",
  "저장된 세션 복구": "Restore saved session",
  "저장된 계획을 읽지 못했습니다.": "Your saved plan could not be read.",
  "손상되었거나 지원하지 않는 세션 형식일 수 있습니다. 원본은 그대로 보존되어 있습니다. 원본을 내보내거나 정상 백업 JSON을 가져온 뒤 복구해 주세요. 새 세션을 시작하면 원본은 별도 브라우저 백업 키에 저장합니다.": "The session may be damaged or use an unsupported format. The original is preserved. Export it or import a valid backup JSON to recover. Starting a new session saves the original under a separate browser backup key.",
  "원본 JSON 내보내기": "Export original JSON",
  "정상 세션 JSON 가져오기": "Import valid session JSON",
  "새 세션 시작": "Start new session",
  "세션 저장 오류": "Session storage error",
  "현재 세션 JSON 내보내기": "Export current session JSON",
  "화면을 여는 중입니다…": "Loading page…",
  "테스트 자산으로": "With test assets,",
  "계획부터 거래 기록까지": "from plans to transaction records",
  "Nile 테스트넷에서 TRX·jTRX 예치·회수와 별도의 PSM USDD·USDT 교환 절차를 검증합니다. 각 거래에는 최신 미리보기, 사용자님 확인, TronLink 서명이 필요합니다.": "Verify TRX / jTRX deposits and withdrawals, plus separate PSM USDD / USDT swaps on Nile testnet. Every transaction requires a fresh preview, your confirmation, and a TronLink signature.",
  "시연 조건 입력": "Set demo conditions",
  "PSM 시험거래 ↓": "PSM test trades ↓",
  "USDT 예상 비교 ↗": "Compare USDT estimates ↗",
  "Nile 시연 준비 상태": "Nile demo readiness",
  "지갑 네트워크": "Wallet network",
  "Nile 주소 연결됨": "Nile address connected",
  "TronLink 연결 전": "TronLink not connected",
  "Nile 블록": "Nile block",
  "이전 블록 조회 · 다시 확인 필요": "Previous block lookup · Refresh required",
  "조회 실패 · 재확인 필요": "Lookup failed · Check again",
  "조회 중": "Loading",
  "저장된 거래 근거": "Saved transaction evidence",
  "거래 기록 없음": "No transaction records",
  "기록은 이 브라우저의 저장값입니다. 확정 영수증과 실제 포지션은 아래 거래 기록에서 별도로 확인합니다.": "Records are saved in this browser. Check confirmed receipts and actual positions separately in the transaction records below.",
  "USDT 예상 비교는 별도입니다.": "USDT estimates are separate.",
  "Mainnet USDT 금액은 지갑 실잔액 검증 없이 가정 조건으로만 계산합니다. Nile TRX 시험 거래를 USDT 투자 성과나 회수 증거로 사용하지 않습니다.": "Mainnet USDT amounts use hypothetical inputs without verifying a real wallet balance. Nile TRX test trades are not evidence of USDT returns or withdrawals.",
  "USDT 가정 시연 보기 ↗": "View USDT scenario demo ↗",
  "Nile 거래 화면을 여는 중입니다…": "Loading Nile transaction screen…",
  "Nile PSM 화면을 여는 중입니다…": "Loading Nile PSM screen…",
  "Mainnet USDT 가정 예시 · 지갑 실잔액과 거래 결과가 아닙니다.": "Hypothetical Mainnet USDT example · Not a real wallet balance or transaction result.",
  "오늘도, 계획하는 사람이": "A plan today creates",
  "더 자유로운 내일을 만듭니다.": "more freedom tomorrow.",
  "지출 날짜를 먼저": "Shall we plan",
  "정해볼까요?": "when you need your funds?",
  "미리 정한 지출이, 더 여유로운 자산 계획의 시작입니다.": "Scheduled expenses are the starting point for a more flexible asset plan.",
  "예정 지출 일정": "Scheduled expenses",
  "이전 7일": "Previous 7 days",
  "다음 7일": "Next 7 days",
  "7일 지출 달력": "7-day expense calendar",
  "예정 지출": "Scheduled expenses",
  "예정된 지출이 없습니다.": "No expenses scheduled.",
  "전 기간 운용 상한 계산": "Full-period allocation ceiling calculation",
  "계획된 지출이 만드는": "Plan your expenses",
  "더 안정적인 오늘": "for a steadier today",
  "지출 일정을 먼저 정하면,": "Schedule your expenses first,",
  "남은 자산을 더욱 현명하게 운용할 수 있습니다.": "then plan how to use the remaining assets.",
  "가상 잔액": "Hypothetical balance",
  "현재 보유한 가상의 자산입니다.": "Your assumed asset balance.",
  "전 기간 운용 상한": "Full-period allocation ceiling",
  "모든 예정 지출액을 따로 보유할 때의": "A hypothetical ceiling with all",
  "가상 운용 상한입니다.": "scheduled expenses held separately.",
  "조건 입력하기": "Enter your conditions",
  "조건을 바꿔 비용 전 이자가 어떻게 달라지는지 살펴보세요.": "Change your inputs to see how interest before costs varies.",
  "오늘의 계획이": "Today's plan,",
  "내일의 여유로": "tomorrow's flexibility",
  "지출 계획부터 정리합니다": "Start with your spending plan",
  "먼저 사용자님이 말한 조건을 JSON으로 확인하고 시장을 조사합니다. 아래 수동 입력은 별도의 가상 시연입니다.": "First, review your stated conditions as JSON and research the market. The manual inputs below form a separate hypothetical demo.",
  "읽기 전용 분석": "Read-only analysis",
  "시연 입력": "Demo inputs",
  "내 조건 입력": "Your conditions",
  "시연 값으로 초기화 ↺": "Reset to demo values ↺",
  "보유 자산": "Asset held",
  "가상 잔고": "Hypothetical balance",
  "보유 금액": "Amount held",
  "운용 기간": "Investment period",
  "일": "days",
  "예정 지출액": "Scheduled expense amount",
  "지출까지 남은 기간": "Days until expense",
  "추가 비상 예비액": "Additional emergency reserve",
  "위험 성향": "Risk preference",
  "보수형": "Conservative",
  "균형형": "Balanced",
  "성장형": "Growth",
  "추가 지출": "Additional expenses",
  "+ 지출 추가": "+ Add expense",
  "금액": "Amount",
  "시점": "Timing",
  "일 뒤": "days later",
  "삭제": "Delete",
  "USDD 경로 검토 의향을 기록합니다. 현재 가정 계산에는 반영되지 않습니다.": "Record willingness to consider the USDD route. This does not affect the current hypothetical calculation.",
  "예정 지출액의 기한 전 운용 위험 수용 의향을 기록합니다. 현재 가정 계산은 지출액을 전액 보호하며 이 선택으로 상한이 늘어나지 않습니다.": "Record willingness to accept the risk of investing scheduled expenses before they are due. This hypothetical calculation protects all expenses; this choice does not increase the ceiling.",
  "지출일 빠르게 비교": "Compare expense dates",
  "7일 뒤": "In 7 days",
  "45일 뒤": "In 45 days",
  "유동성 계산 결과": "Liquidity calculation results",
  "유동성 계산": "Liquidity calculation",
  "자동 계산": "Automatic calculation",
  "입력값을 확인해 주세요": "Please check your inputs",
  "건과 비상 예비액을 전액 확보한 뒤의 상한입니다. 날짜별 회수 후보나 거래 조건은 이번 가정 계산에 포함하지 않습니다.": "and your emergency reserve are fully protected. Dated withdrawal candidates and trade conditions are not included in this hypothetical calculation.",
  "지출·예비액": "Expenses and reserve",
  "입력 버전": "Input version",
  "사용자님 확인 완료": "Confirmed by you",
  "확인 전": "Not confirmed",
  "확인 완료": "Confirmed",
  "입력 요약 확인": "Confirm input summary",
  "출금 시점과 거래비용은 별도 상품 검증이 필요합니다. 위 금액은 예치 권고나 실행 가능 금액이 아닙니다.": "Withdrawal timing and transaction costs require separate product verification. The amount above is neither a deposit recommendation nor an executable amount.",
  "다음 단계": "Next step",
  "입력한 조건의 가정 결과를 확인해 보세요.": "Review the hypothetical result for your inputs.",
  "가정 계산 ↗": "Scenario calculator ↗",
  "Mainnet USDT 읽기 전용 비교": "Read-only Mainnet USDT comparison",
  "먼저 입력 조건의 고정 예시를 보여주고, 아래에서 공식 원천을 별도로 조회합니다.": "First view a fixed example for your inputs, then query official sources separately below.",
  "왕복 비용과 순익이 확인되지 않아 상품을 추천하거나 거래하지 않습니다.": "Round-trip costs and net returns are unverified, so no product is recommended or traded.",
  "조건 수정 ↗": "Edit conditions ↗",
  "Mainnet 날짜별 상품 비교": "Mainnet products by date",
  "날짜별 상품 경로 비교": "Compare product routes by date",
  "확인한 지출 조건으로 보유·jUSDT·PSM→jUSDD를 비교합니다. 용량과 왕복 비용이 빠지면 운용 후보에서 제외합니다.": "Compare holding, jUSDT, and PSM → jUSDD against your confirmed expenses. Routes without verified capacity and round-trip costs are excluded.",
  "실제 시연": "Live test demo",
  "Nile TRX 시험 거래는 별도 체인에서 진행합니다.": "Nile TRX test trades take place on a separate chain.",
  "Nile 시연으로 ↗": "Go to Nile demo ↗",
  "공식 시장 데이터": "Official market data",
  "JustLend V1 Mainnet 시장 조회값입니다. 원천 갱신 시각은 제공되지 않으며 인센티브 수익률은 포함되지 않습니다.": "JustLend V1 Mainnet market readings. Source update timestamps are unavailable, and incentive yields are excluded.",
  "자산 검색": "Search assets",
  "조회 중…": "Loading…",
  "↻ 다시 조회": "↻ Refresh",
  "공식 API에서 시장을 조회하고 있습니다…": "Fetching markets from the official API…",
  "실시간 시장 조회 실패": "Live market lookup failed",
  "최근 API 조회 · MAINNET": "Recently fetched · MAINNET",
  "지난 API 조회 · 다시 조회 필요": "Previous API reading · Refresh required",
  "개 시장": " markets",
  "조회 시각": "Fetched at",
  "시장": "Market",
  "기본 예치 APY": "Base supply APY",
  "대출 APY": "Borrow APY",
  "시장 현금 · 원자산 단위": "Market cash · underlying units",
  "일치하는 시장이 없습니다.": "No matching markets.",
  "공식 API 원문 ↗": "Official API response ↗",
  "원천 갱신 시각:": "Source updated at:",
  "제공되지 않음": "Not provided",
  "· 활성/legacy 여부 미확인 · 화면 표시 기준 5분": "· Active / legacy status unverified · 5-minute display freshness window",
  "데이터 범위": "Data scope",
  "Mainnet 시장과 Nile 개발 지갑은 별도 환경입니다.": "Mainnet markets and the Nile development wallet are separate environments.",
  "연결 상태 ↗": "Connection status ↗",
  "개발 환경 연결 상태": "Development connections",
  "연결은 주소만 조회합니다. Nile 거래는 미리보기와 사용자님 확인을 거칩니다.": "Connecting only reads your address. Nile transactions require a preview and your confirmation.",
  "TronLink 주소 연결": "Connect TronLink address",
  "다시 확인": "Check again",
  "주소 연결": "Connect address",
  "연결 확인 필요": "Connection check required",
  "연결 확인 중": "Checking connection",
  "Nile 테스트넷 최신 블록을 조회하고 있습니다.": "Fetching the latest Nile testnet block.",
  "최근 조회": "Recently fetched",
  "다시 조회 필요": "Refresh required",
  "연결 실패": "Connection failed",
  "확인 중": "Checking",
  "다시 조회 ↗": "Refresh ↗",
  "계약·시장·수수료 검증이 통과하면 Nile 계획에서 미리보기와 사용자님 확인을 진행할 수 있습니다.": "Once contract, market, and fee checks pass, you can preview the Nile plan and confirm it.",
  "Nile 시작 화면 ↗": "Nile home ↗",
  "Nile TRX는 테스트넷 · USDT 수치는 가정 시나리오 · Mainnet 시장 조회는 별도": "Nile TRX: testnet · USDT figures: hypothetical · Mainnet market lookup is separate",
  "운용 기간과 지출일을 정수로 입력해 주세요.": "Enter whole numbers for the investment period and expense dates.",
  "금액·운용 기간·지출일을 확인해 주세요. 기간과 지출일은 1~3650일입니다.": "Check amounts, the investment period, and expense dates. Periods and dates must be within 1\u20133,650 days.",
  "금액을 0 이상의 숫자로 입력해 주세요.": "Enter amounts as non-negative numbers.",
  "운용 기간과 지출일은 1~3650일로 입력해 주세요.": "Enter an investment period and expense dates within 1\u20133,650 days.",
  "보유 금액은 0보다 커야 합니다.": "The amount held must be greater than zero.",
  "예정 지출이 보유 금액보다 큽니다.": "Scheduled expenses exceed the amount held.",
  "지출액과 예비액의 합계가 보유 금액보다 큽니다.": "Expenses plus the reserve exceed the amount held.",
  "운용 기간은 1~3650일이어야 합니다.": "The investment period must be 1\u20133,650 days.",
  "다른 자산으로 지급할 지출에는 검증된 자산 전환 경로가 필요합니다.": "Expenses in another asset require a verified conversion route.",
  "예정 지출액과 여유액의 합계가 보유 금액보다 큽니다.": "Scheduled expenses plus the reserve exceed the amount held.",
  "Chrome에서 TronLink를 설치한 뒤 페이지를 새로고침해 주세요.": "Install TronLink in Chrome, then refresh this page.",
  "지갑 잠금 해제와 연결 승인을 완료해 주세요.": "Unlock your wallet and approve the connection.",
  "승인된 TronLink 계정과 현재 계정이 다릅니다.": "The approved TronLink account differs from the current account."
};

const korean = Object.fromEntries(Object.entries(english).map(([ko, en]) => [en, ko]));
export function mainCopy(value: string, language: Language): string {
  return (language === 'en' ? english[value] : korean[value]) ?? value;
}
